import time

while True:
    print('1', end='\r')
    time.sleep(1)
    print('2', end='\r')
    time.sleep(1)
    print('3', end='\r')
    time.sleep(1)
    print('4', end='\r')
    time.sleep(1)
    print('5', end='\r')
    time.sleep(1)
    print('6', end='\r')
    time.sleep(1)
    print('7', end='\r')
    time.sleep(1)
    print('8', end='\r')
    time.sleep(1)
    print('9', end='\r')
    time.sleep(1)
